#!/usr/bin/env bash
# displays Holberton School 10 times
Hour=0; while((Hour<=12)); do echo "Hour: ${Hour}"; minutes=1; while((minutes<=59)) ;do echo "${minutes}"; ((++minutes)); done; ((++Hour)); done
